### Get All PostTags
GET http://localhost:8080/postTags
Content-Type: application/json
Cookie: jwt="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlRlc3QgVXNlciIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTY4NDQ2ODkxMSwiZXhwIjoxNjg0NTU1MzExfQ.1Vyr__OGtLYeT8zE9gXGT5HwYIiBqMK5PNfVad-hRQc"

###

### Create a New PostTag
POST http://localhost:8080/postTags
Content-Type: application/json
Cookie: jwt="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlRlc3QgVXNlciIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTY4NDQ2ODkxMSwiZXhwIjoxNjg0NTU1MzExfQ.1Vyr__OGtLYeT8zE9gXGT5HwYIiBqMK5PNfVad-hRQc"

{
  "postId": 1,
  "tagId": 1
}

###

### Update an Existing PostTag
PUT http://localhost:8080/postTags/1
Content-Type: application/json
Cookie: jwt="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlRlc3QgVXNlciIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTY4NDQ2ODkxMSwiZXhwIjoxNjg0NTU1MzExfQ.1Vyr__OGtLYeT8zE9gXGT5HwYIiBqMK5PNfVad-hRQc"

{
  "postId": 1,
  "tagId": 2
}

###

### Delete an Existing PostTag
DELETE http://localhost:8080/postTags/1
Content-Type: application/json
Cookie: jwt="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlRlc3QgVXNlciIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTY4NDQ2ODkxMSwiZXhwIjoxNjg0NTU1MzExfQ.1Vyr__OGtLYeT8zE9gXGT5HwYIiBqMK5PNfVad-hRQc"

###
``