### Get All Tags
GET http://localhost:8080/tags
Content-Type: application/json
Cookie: jwt="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlRlc3QgVXNlciIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTY4NDQ3NjU3MSwiZXhwIjoxNjg0NTYyOTcxfQ.7UceXHOxmzt0AlAfIpjmfcpURmY9tsvloAsikGq3iwE"

###

### Get a Single Tag with associated posts
GET http://localhost:8080/tags/1
Content-Type: application/json
Cookie: jwt="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlRlc3QgVXNlciIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTY4NDQ2ODkxMSwiZXhwIjoxNjg0NTU1MzExfQ.1Vyr__OGtLYeT8zE9gXGT5HwYIiBqMK5PNfVad-hRQc"

###


### Create a New Tag
POST http://localhost:8080/tags
Content-Type: application/json
Cookie: jwt="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlRlc3QgVXNlciIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTY4NDQ3NjU3MSwiZXhwIjoxNjg0NTYyOTcxfQ.7UceXHOxmzt0AlAfIpjmfcpURmY9tsvloAsikGq3iwE"

{
  "name": "New Tag2"
}

###

### Update an Existing Tag
PUT http://localhost:8080/tags/1
Content-Type: application/json
Cookie: jwt="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlRlc3QgVXNlciIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTY4NDQ2ODkxMSwiZXhwIjoxNjg0NTU1MzExfQ.1Vyr__OGtLYeT8zE9gXGT5HwYIiBqMK5PNfVad-hRQc"

{
  "name": "Updated Tag"
}

###

### Delete an Existing Tag
DELETE http://localhost:8080/tags/1
Content-Type: application/json
Cookie: jwt="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlRlc3QgVXNlciIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTY4NDQ2ODkxMSwiZXhwIjoxNjg0NTU1MzExfQ.1Vyr__OGtLYeT8zE9gXGT5HwYIiBqMK5PNfVad-hRQc"

###
