### Register a new user
POST http://localhost:8080/register
Content-Type: application/json

{
    "name": "Test User",
    "password": "password123",
    "email": "test@example.com",
    "isAdmin": false
}

### Login a user
POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password123"
}

### Access a protected route
### Before sending this request, replace YOUR_TOKEN_HERE with the JWT you received when logging in.
GET http://localhost:8080/protected
Cookie: jwt="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlRlc3QgVXNlciIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTY4NDIzMzUxOSwiZXhwIjoxNjg0MzE5OTE5fQ.Q8THa7GQDhTylja6h8jRQVSlNvQkc5CGEEdyuQT0Hs4"

###

GET http://localhost:8080/me
Cookie: jwt="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlRlc3QgVXNlciIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTY4NDIzMzUxOSwiZXhwIjoxNjg0MzE5OTE5fQ.Q8THa7GQDhTylja6h8jRQVSlNvQkc5CGEEdyuQT0Hs4"